### ISSUE TITLE
knowledge bar lightbulb missing

### ISSUE THREAD

**Issue by tommon29** [udacity/blockchain-nanodegree-issues#1]
In lesson 1 part 7 (nanodegree resources) the lesson states that "You should be able to access Knowledge anytime by clicking on the lightbulb on the left hand side of the classroom." I am not able to find the lightbulb, and another user in the classroom chat mentioned that they could not see it either.

**Comment by Ravisarkar** [comment]
have the same issue

**Comment by jperera84** [comment]
Perfect, thanks for let us know. I'm going to close the ticket, if someone have any issue in the future we can reopen it.
