### ISSUE TITLE
Wrong log message

### ISSUE THREAD

**Issue by rafaelbrasilia** [udacity/blockchain-nanodegree-issues#100]

**Comment by rafaelbrasilia** [comment]
This should say SHA256 instead of SHA265
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd12c199aa41b001130e48b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a17f2481e129bb4428505c5f4cac41590a17f9fa8f2fafa42062c80d55b98e30063e937f03a6aa8317b500bf248b4b86b3bc8d4cc1ef3f37aa.JPG)

**Comment by jperera84** [comment]
This has being fixed, to see the change you should reset your data in the workspace, be careful that erase all the code you already wrote.
