### ISSUE TITLE
Typo in practice hashing

### ISSUE THREAD

**Issue by asolomon15** [udacity/blockchain-nanodegree-issues#101]

**Comment by asolomon15** [comment]
Hello, 

Just noticed that there is a typo in the "practice hashing" java script section.

"Step 2. Import from crypto-js module the sha265 library"  

Shouldn't this be sha256 ?

**Comment by jperera84** [comment]
Thanks for let us know if fixed this, to see the change use reset data in your workspace, be careful that operation erase any code you already wrote.
