### ISSUE TITLE
Lesson 2 - Concept "9. Sign a Transaction"

### ISSUE THREAD

**Issue by thom** [udacity/blockchain-nanodegree-issues#102]

**Comment by thom** [comment]
Link in section "Upcoming Workspace" to "Workspace: Verify Message Signature" (https://classroom.udacity.com/nanodegrees/nd1309/parts/53eb3bf0-8a05-45ff-b11d-8b993fb8f10b/modules/0337fa81-d6b9-40f0-99aa-891db36c8bbc/lessons/897f4768-6cff-4642-afe3-ed9150bc9f07/concepts/54e9f8fd-85b9-44b9-8cdd-08dec2d969d0) is not working.

**Comment by jperera84** [comment]
Thanks for the feedback but I didn't find the concept you are referring is the link you are sending working?

**Comment by thom** [comment]
In https://classroom.udacity.com/nanodegrees/nd1309/parts/53eb3bf0-8a05-45ff-b11d-8b993fb8f10b/modules/0337fa81-d6b9-40f0-99aa-891db36c8bbc/lessons/78c201d3-b69b-47b8-b992-821a1162d32f/concepts/d701db88-2e37-41a2-8876-17f209fab2be there is a link at the bottom called "Workspace: Verify Message Signature" which leads to the non-existent target https://classroom.udacity.com/nanodegrees/nd1309/parts/53eb3bf0-8a05-45ff-b11d-8b993fb8f10b/modules/0337fa81-d6b9-40f0-99aa-891db36c8bbc/lessons/897f4768-6cff-4642-afe3-ed9150bc9f07/concepts/54e9f8fd-85b9-44b9-8cdd-08dec2d969d0.

**Comment by jperera84** [comment]
Thanks for the feedback, this has been fixed.
