### ISSUE TITLE
Lesson 4 Blockchain data

### ISSUE THREAD

**Issue by ish3lan** [udacity/blockchain-nanodegree-issues#104]
Previous output hash - All inputs reference back to an output (UTXO). This points back to the transaction containing the UTXO that will be spend in this input. The hash value of this UTXO is saved in a reverse ordered here.*

and the star points to:

*Remember that all inputs reference back to an output (UTXO). This points back to the transaction containing the UTXO that will be spend in this input. The hash value of this UTXO is saved in a reverse ordered here.

I guess copying the same text is mistake

**Comment by jperera84** [comment]
Thanks for the feedback, this has been fixed.
