### ISSUE TITLE
Typo in Lesson 1: Blockchain basics -> 12. Consensus

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#109]
In Lesson 1: Blockchain Basics -> 12. Consensus, the term Byzantine General's problem is referenced, but according to Wikipedia (https://en.wikipedia.org/wiki/Byzantine_fault_tolerance#Byzantine_Generals'_Problem) and other sources it should be Byzantine Generals' problem (i.e., a problem belonging to all of the generals collectively), or the Byzantine Generals Problem (with no possessive ' anywhere—this version seems to be the way it was written in the paper where it first appeared)

**Comment by jperera84** [comment]
You are right I'm fixing this to use Byzantine Generals' problem consistently.
