### ISSUE TITLE
Typos in Lesson 1: Blockchain basics -> 17: Recep of Achieving Consensus Protocols

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#113]
Just a few typos I noticed in this lesson:

"As we saw in the Byzantines’ General Problem..." should be "As we saw in the Byzantine Generals' Problem..."

"...Bitcoin’s white paper is using proof of work (POW)..." should maybe be "...Bitcoin’s white paper is using Proof of Work (PoW)..." to be consistent with use of "PoW" elsewhere in the course.

"2. A Monopoloy of Miners which Leads to..." should be "2. A Monopoly of Miners which Leads to..."

"It is up to users of protocol who vote on Delegates..." should maybe be "It is up to users of the protocol who vote on Delegates...". I'm not sure about this one?

Thanks for all of your hard work!!

**Comment by liamseanbrady** [comment]
Oh, I also wondered whether the title of this lesson should be "Recap of Achieving Consensus" instead of "Recap of Achieving Consensus Protocols", because the title on the page itself is "Recap of Achieving Consensus"?

**Comment by jperera84** [comment]
I took care about this issues and thanks also for the recommendation.
