### ISSUE TITLE
Typo in Lesson 2: Blockchain Transactions -> 4. Wallet Overview

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#115]
In the 'Wrapping Up' section at the bottom of this page, it says "…and a even distinct types of deterministic wallets like HD wallets…" and it seems like it should be "…and even distinct types of deterministic wallets like HD wallets…"?

Hopefully that's helpful!

**Comment by jperera84** [comment]
As always very helpful, it is fixed now, thanks
