### ISSUE TITLE
Typos in Lesson 2: Blockchain Transactions -> 5. Wallet Types

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#116]
Just a few minor typos I spotted on this page…

"First, lets take a closer look at…" should be "First, let's take a closer look at…"

"…a variety of scenarios for you explore." should be "a variety of scenarios for you to explore."

"…generate an unique transaction…" should be "…generate a unique transaction…"

In the questions at the bottom, none of the other questions start with "Scenario X:", but the third one starts with "Scenario 3: A shoe supply chain…" and it probably isn't necessary since the other questions/scenarios aren't numbered.

Thanks!

**Comment by jperera84** [comment]
Thanks, Liam, I think I fixed all the issues you mentioned here, thanks.
