### ISSUE TITLE
Typo and possible wording change for Lesson 3: Verify Message Signature -> 4. Step 2: Sign a Message

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#118]
"If the private key or the wallet address or the signature or the message has been were altered..." should be "If the private key or the wallet address or the signature or the message were altered..."

"If the private key or the wallet address or the signature or the message were altered, a different digital signature would be produced and hence the authentication will fail." might read a little more naturally if commas were used to separate the options rather than successive "or"s, e.g., "If the private key, wallet address, signature or message were altered, a different digital signature would be produced and hence the authentication will fail.". This is stylistic, but it reads a little more naturally to me and make what's being said a little clearer.

Hopefully that all makes sense. Thanks!

**Comment by liamseanbrady** [comment]
Oh, I also just spotted on the same page: "Authentication - A valid digital signature proves to the recipient, that the message was sent by a known sender." could probably be "Authentication - A valid digital signature proves to the recipient that the message was sent by a known sender.", basically just removing the comma to make the sentence read naturally without a break.

**Comment by jperera84** [comment]
This is fixed, thanks
