### ISSUE TITLE
Typos in Lesson 3: Verify Message Signature -> 6. Quiz: Verify Message Signature

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#119]
"To confirm if the package has been installed: In the terminal run:", could maybe be written more clearly as "To confirm if the package has been installed, in the terminal run:"

"...which signatures Verify to be "TRUE" and which signatures verify to..." should probably be "...which signatures Verify to be "TRUE" and which signatures Verify to..." to stay consistent with using "Verify" with a capital "V" everywhere.

**Comment by jperera84** [comment]
Fixed, Thanks
