### ISSUE TITLE
Typo in Project: Managing your Blockchain Identity -> 4. Project: Managing your Blockchain Identity

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#122]
In the sentence below

"To successfully complete this project and meet the rubric criteria, provide create document your values for the following components in a text file"

I'm not sure if "…provide create document your values…" is correct? It seems like it should be either "provide your values", "create your values", or "document your values".

Thanks!

**Comment by jperera84** [comment]
Thanks, Liam, I fixed this.
