### ISSUE TITLE
Typo in Blockchain Data -> Lesson 1: Blockchain Data Overview -> 4. Do You Need a Blockchain?

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#124]
In the sentence "Given the news and headlines about the blockchain it might seems like its the perfect fit for every situation", "seems" should be "seem", and "its" should be "it's"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/808abc06-4959-499c-9c31-54be1838096f/concepts/3ecab91f-d8f9-4fbf-ac46-fe0f74c43f0c

Thanks!

**Comment by jperera84** [comment]
Thanks, Liam I fixed this.
