### ISSUE TITLE
Typo in Blockchain Data -> Lesson 1: Blockchain Data Overview -> 8. Explore Blockchain Data

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#126]
In the second paragraph of the 'Wrap Up' section "…and allow you solve more complex problems…" should be "…and allow you to solve more complex problems…"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/808abc06-4959-499c-9c31-54be1838096f/concepts/2638b316-58fb-48b3-b2a9-5730bfae8c14#wrap-up

Thanks!

**Comment by jperera84** [comment]
Fixed this. Thanks
