### ISSUE TITLE
an issue with opening a Workspace

### ISSUE THREAD

**Issue by inherithandle** [udacity/blockchain-nanodegree-issues#127]
I've checked out the documentation Enable Third-Party Cookies in Safari, https://udacity.zendesk.com/hc/en-us/articles/115004653246. but It is now outdated. I cannot find the option "Allow from websites I visit". How can I enable Third-Party Cookies? my safari version is 12.0.1 (14606.2.104.1.1)

I am seeing the following error message:
We are unable to load your Workspace.
This can occur if you have blocked third party cookies in your browser. For detailed instructions on how to fix this error follow the link below. How To Enable Third Party Cookies For Workspaces

Redirecting failed to save a cookie at "https://viewj2tmrc7i5wn.udacity-student-workspaces.com". This is necessary to establish a connection to the remote machine. The browser was last redirected seconds ago on Wednesday, December 19th 2018, 4:23:05 pm
Wed Dec 19 2018 16:23:05 GMT+0900 (KST) 1371138535

**Comment by inherithandle** [comment]
the issue resolved by unchecking Prevent cross-site tracking, From Preferences -> Privacy. I still don't know it would be safe. anyway closed. 

![screen shot 2018-12-19 at 4 31 40 pm](https://user-images.githubusercontent.com/5329036/50205448-94aa7200-03ab-11e9-8ba5-1c97c42b8ad7.png)

**Comment by dishha** [comment]
Hi, 
I am having the same issue. How did you resolve this problem?

**Comment by dishha** [comment]
Hi, 
I am facing the same problem. How did you resolve this issue?

**Comment by myaccountstlee** [comment]
> the issue resolved by unchecking Prevent cross-site tracking, From Preferences -> Privacy. I still don't know it would be safe. anyway closed.
> 
> ![screen shot 2018-12-19 at 4 31 40 pm](https://user-images.githubusercontent.com/5329036/50205448-94aa7200-03ab-11e9-8ba5-1c97c42b8ad7.png)

I tried this on my MacBook Pro with Safari and it did not work
