### ISSUE TITLE
Typo in Project: Private Blockchain > Step 4

### ISSUE THREAD

**Issue by iluu** [udacity/blockchain-nanodegree-issues#128]
Paragraph: Configure LevelDB to persist dataset

1) Mentions a sample file: `leveldbSandbox.js` in the first sentence. The file name should be `levelSandbox.js` instead.

2) Code formatting is missing in the following section:

> The leveldbSandbox.js file already has a few basic functions implemented for you: addLevelDBData(key,value) addDataToLevelDB(value) getLevelDBData(key)

Classroom link:
https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/1abdf0a2-f349-4876-9434-77e7588cc762/concepts/03f7e2ec-f02a-4959-bd09-46f225abf4c0

**Comment by jperera84** [comment]
Everything is fixed now, thanks for the feedback
