### ISSUE TITLE
Can you please use UTC time zone

### ISSUE THREAD

**Issue by thelukemccarthy** [udacity/blockchain-nanodegree-issues#13]
Hi
When putting times on events etc can you also use the UTC timezone. This makes it much easier for those of us not in the USA

**Comment by jperera84** [comment]
Could you specify a little bit this issue, the UTC timezone that you want to use is referring a particular with a lesson or video?

**Comment by thelukemccarthy** [comment]
I talking about times of events. For example "Experts in Residence" Office Hours, and, "Ask Me Anything" sessions

**Comment by jperera84** [comment]
Thanks, I got what you are saying, we are going to do this.
