### ISSUE TITLE
Typo (?) in Blockchain Data -> Lesson 1: Blockchain Data Overview -> 12. Quiz: Softfork vs Hardfork

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#131]
In the previous section (11. BIPs and Forks), the three types of 'forks' mentioned are Softforks, Hardforks, and Source Code Forks, but in this section (12. Quiz: Softforks vs Hardforks) Source Code Forks are now referred to as Software Forks. This seems a little confusing. It might be helpful to stick with either Source Code Forks, or Software Forks (or, add a note in '11. BIPs and Forks' to say that Source Code Forks are also known as Software Forks).

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/808abc06-4959-499c-9c31-54be1838096f/concepts/88165ad3-b3a7-470f-a4b5-e2fc3ffe6eab

Thanks!

**Comment by jperera84** [comment]
Thanks, moving to "Source Code Forks"
