### ISSUE TITLE
Typo in Blockchain Data -> Lesson 2: Bitcoin Core Testnet -> 11. Get Testnet Coins

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#133]
At the bottom of the page there is a note which says "Note: If your Bitcoin Core haven't synchronized completely your Tesnet network, this operation can be delayed until the network is synchronized".

This might read more clearly as: "Note: If your Bitcoin Core has not synchronized completely with your Tesnet network, this operation can be delayed until the network is synchronized"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/8abea3d8-b174-4f57-ad1d-03bc1bf0f68d/concepts/f47636c9-4858-420b-8bc0-24f104109939

Thanks!

**Comment by jperera84** [comment]
This has been fixed Liam, thanks
