### ISSUE TITLE
Typo in Blockchain Data -> Lesson 4: Blockchain Data -> 3. Blockchain Data Models Overview

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#134]
"…solving for the nonce what when added to…" should probably be "…solving for the nonce that when added to…"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/9a0c1f4d-250c-4de8-ae56-da22c2acd033

Thanks!

**Comment by jperera84** [comment]
Thanks, fixed now
