### ISSUE TITLE
Typo in Blockchain Data -> Lesson 4: Blockchain Data -> 6. Bitcoin Scripts

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#136]
"Transaction in the bitcoin blockchain are stored…" should be "Transactions in the bitcoin blockchain are stored…"

"The hash value of this UTXO is saved in a reverse ordered here" should be "The hash value of this UTXO is saved in a reverse order here"

"This s a deprecated feature of bitcoin Currently set to…" should be "This is a deprecated feature of bitcoin, currently set to…"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/0009a0a0-0fd4-44fe-b530-bce579e6a9f3

Thanks!

**Comment by jperera84** [comment]
Fixed the issues, thanks
