### ISSUE TITLE
Broken/stale links in Blockchain Data -> Lesson 4: Blockchain Data -> 6. Bitcoin Scripts

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#137]
Under the 'Code Examples' section at the bottom of the page, there are two links to the 'wallet.cpp' file in the Bitcoin GitHub repo. The first link is supposed to link to an example of 'scriptPubKey', but it now links to a random line in the code: 'fUpdated = true;'. This is probably because a previous version of this file contained the relevant code on this line, but has now been updated. I think this can be fixed by creating a permalink to the relevant line of code (which links to the line at that point in time) instead of a link to just that line number in the master branch (which is likely to change). The second link is supposed to link to an example of 'scriptSig', but for me is going to a Udacity 404 page.

Hopefully that makes sense!

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/0009a0a0-0fd4-44fe-b530-bce579e6a9f3

Thanks!

**Comment by liamseanbrady** [comment]
For reference, I think the permalink for the 'scriptSig' example is supposed to be: https://github.com/bitcoin/bitcoin/blob/feda41e0a7c4440d398516850f9cbd4c4f3192dd/src/wallet/wallet.cpp#L1930-L1937.

**Comment by jperera84** [comment]
Fixed, thanks
