### ISSUE TITLE
Stale instructions (?) in Blockchain Data -> Lesson 4: Blockchain Data -> 8. Quiz: Opcodes

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#138]
Under the 'Exploring Live Scripts' section, for 'Step 2.', there is an instruction which says "Scroll down to the bottom to see the Unlocking Scripts…", but now on the UI for the block explorer you need to go to the 'Inputs and Outputs' table, find the 'Scripts' header, and then click on 'Show scripts & coinbase' in order to see the scripts for the transaction.

Also, I noticed that all of the steps for the instructions are titled 'Step 2., Step 3., Step 4., etc', but what should be 'Step 1.' is just '1. '

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/e347029d-1861-4d2a-8175-47413060c2fd

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
