### ISSUE TITLE
Typo in Blockchain Data -> Lesson 4: Blockchain Data -> 12. Setup for Creating a Transaction

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#140]
In the 'Environment Setup' section at the bottom of the page, there is a bullet point that says:

"- Type in the command line . You can also add a label for your address by typing, ."

The commands are missing. It seems like it should be something like:

"Type in the command line getnewaddress. You can also add a label for your address by typing, getnewaddress [label]."

It looks like there's a '<getnewaddress>' element in the HTML that's supposed to be doing this, but it's not rendering anything for me in Chrome.

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/c21bc6f6-f8e9-4cea-8021-118ddd6b23bf

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
