### ISSUE TITLE
Typo in Blockchain Data -> Lesson 2: Blockchain Transactions -> 5: Wallet Types -> Scenario 2 Question

### ISSUE THREAD

**Issue by Z0MP** [udacity/blockchain-nanodegree-issues#141]

**Comment by Z0MP** [comment]
"I’m creating a web server that sells widgets and want to generate an unique transaction address for every customer and every address and track it independently."

"an unique transaction" -> "a unique transaction"

**Comment by jperera84** [comment]
Fixed, thanks
