### ISSUE TITLE
Unexplained term in Blockchain Data -> Lesson 4: Blockchain Data -> 15. Create a Transaction: Step 3

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#142]
In the 'Explanation' section, it says "Let's also assume that our gas would cost us…", but this has previously been exclusively called a 'transaction fee'.

It might be helpful to put in a note here to say that 'gas' is another name for 'transaction fee'

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/ea1d958a-7ddc-4a17-bec2-5e2626c7bce8

Thanks!

**Comment by jperera84** [comment]
You are right, actually `gas` isn't a term valid for Bitcoin, I fixed this.

**Comment by liamseanbrady** [comment]
Awesome—thanks so much for clearing that up. That's very helpful to know that!
