### ISSUE TITLE
Typo and unclear instructions in Blockchain Data -> Lesson 4: Blockchain Data -> 17. Create a Transaction: Step 5

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#143]
"This is because we have not signed the transaction yet to prove, that we own the address…" should be "This is because we have not signed the transaction yet to prove that we own the address…", without the extra "," separating the sentence.

On the page, it says "Note: If you have a version of Bitcoin core that is older than 0.17, you might have to use command.", but it's unclear as to what "use command" means.

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/b7d8b181-3159-4afc-97e4-f9f98513e8f1

Thanks!

**Comment by jperera84** [comment]
Fixed, Thanks
