### ISSUE TITLE
Typo in Blockchain Data -> Lesson 5: Private Blockchains -> 1. Lesson Introduction

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#144]
"Build from scratch a simple private blockchain that creates new blocks, store data in blocks, and secure blocks with a digital signature using a one-way hash." should be "Build from scratch a simple private blockchain that creates new blocks, stores data in blocks, and secures blocks with a digital signature using a one-way hash."

The sub-heading "Follow the code sessions local" should be "Follow the code sessions locally"

"If you want to follow the code from your own computer you can do it cloning…" should be "If you want to follow the code from your own computer you can do it by cloning…"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/24197b75-77c9-476b-9595-7a1fe086d19b

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
