### ISSUE TITLE
Typo in Blockchain Data -> Lesson 5: Private Blockchains -> 7. Create New Blocks

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#145]
"…finally created simpleChain.js with a Block class, Constructor, and related. Variables." should be "…finally created simpleChain.js with a Block class, Constructor, and related Variables."

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/b1540463-631d-401a-a24e-f6d919e38aca

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
