### ISSUE TITLE
Typo in Blockchain Data -> Lesson 5: Private Blockchains -> 9. Link Blocks

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#146]
"Modified addblock function to include generation of our block hash" should be "Modified addBlock function to include generation of our block hash"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/5673c38b-3460-4bee-a661-28e5ba05c993

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
