### ISSUE TITLE
Typo in Blockchain Data -> Lesson 5: Private Blockchains -> 11. Practice LevelDB and Promises

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#148]
"Promises allow us to work with the database in asynchronous way" should be "Promises allow us to work with the database in an asynchronous way"

"The fist method implemented is…" should be "The first method implemented is …"

"This method allow you to get the value that corresponds to a certain key." should be "This method allows you to get the value that corresponds to a certain key."

"This method allow you to insert data into the LevelDB." should be "This method allows you to insert data into the LevelDB."

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/2d6960f0-93e5-45a2-bb75-09a9f6c6c2e2#

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
