### ISSUE TITLE
Typos in Blockchain Data -> Project: Private Blockchain -> 1. Project Introduction

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#149]
"In this project you will put this knowledge to practice by…" should be "In this project you will put this knowledge into practice by…"

"A core responsibilities of a blockchain nodes is to…" should be "A core responsibility of blockchain nodes is to…"

"Infact, Bitcoin core uses…" should be "In fact, Bitcoin core uses…"

"Implement basics functionalities for your Private Blockchain" should be "Implement basic functionalities for your Private Blockchain"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/1abdf0a2-f349-4876-9434-77e7588cc762/concepts/249e5f25-4ce0-44e0-a0d6-8fbbb44fd55e#

Thanks!

**Comment by jperera84** [comment]
Fixed, Thanks
