### ISSUE TITLE
Typo in Blockchain Data -> Project: Private Blockchain -> 4. Step 2: Modify Functions to Persist Data

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#150]
"Make sure the genesis block persist as the first block…" should be "Make sure the genesis block is persisted as the first block…"

"The leveldbSandbox.js file already has…" should be "The levelSandbox.js file already has…"

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/1abdf0a2-f349-4876-9434-77e7588cc762/concepts/03f7e2ec-f02a-4959-bd09-46f225abf4c0#

Thanks!

**Comment by jperera84** [comment]
Fixed it, thanks
