### ISSUE TITLE
Comment/instruction typos in nd1309-work-code/Course_Blockchain_Data/Project_2_es6_starter_code/LevelSandbox.js

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#152]
"// Add your code here, remember un Promises…" should be "// Add your code here, remember in Promises…"

Link to one of the comments: https://github.com/udacity/nd1309-work-code/blob/300a6e7c5b8612d4f83c085156619c0d638b7a54/Course_Blockchain_Data/Project_2_es6_starter_code/LevelSandbox.js#L18

The typo is also repeated on lines 26 and 34.

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
