### ISSUE TITLE
Comment/instruction typos in nd1309-work-code/Course_Blockchain_Data/Project_2_es6_starter_code/BlockChain.js

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#153]
Example of typo: https://github.com/udacity/nd1309-work-code/blob/4be7ccb21bba155c05d337d1d0d1c48a8e8d40b6/Course_Blockchain_Data/Project_2_es6_starter_code/BlockChain.js#L16

'Auxiliar' is used to describe the 'auxiliary' or 'helper' functions like 'generateGenesisBlock()' and 'getBlockHeight()'. Generally, I've seen these called 'helper' functions more than 'auxiliary' functions.

It occurs on lines 16, and 24.

Thanks!

**Comment by jperera84** [comment]
Fixed, thanks
