### ISSUE TITLE
Typo in Blockchain Web Services -> Lesson 1: Planning a WebService -> 3. What is a Web Service

### ISSUE THREAD

**Issue by iluu** [udacity/blockchain-nanodegree-issues#157]
### Second paragraph of  `Protocols` section:

> While UDDI transmits. WSDL files instead ofstandard.XML files, it may still use the SOAP protocol to transfer data.

instead it should be:

> While UDDI transmits WSDL files instead of standard XML files, it may still use the SOAP protocol to transfer data.

### Third paragraph of `Protocols`:
> The other most common protocol is REST is a design style for protocols, it was developed by Roy Fielding in his Ph.D. dissertation and formalized the approach behind HTTP/1.0, finding what worked well with it, and then using this more structured understanding of it to influence the design of HTTP/1.1. So, while it was after-the-fact in a lot of ways, REST is the design style behind HTTP.

This is just hard to read ;) Someone should re-edit it maybe ?

Classroom link: 
https://classroom.udacity.com/nanodegrees/nd1309/parts/c4ecd959-25d3-46c3-91ba-e5d79c638a34/modules/66945d17-26b1-4370-9b8c-466f4fd3e6ff/lessons/35a29f3e-aa24-414d-bf6f-726123ccba68/concepts/3c1168ad-188b-4b92-8d11-b8e013cd3e79

**Comment by jperera84** [comment]
Thanks for the feedback, I fixed this.
