### ISSUE TITLE
Incorrect answer for Lesson 7, Chap 6 "What is the merkle root for block 1000?"

### ISSUE THREAD

**Issue by kokobird** [udacity/blockchain-nanodegree-issues#16]
The correct Merkle Root is none of the available options.

Since I cannot upload an image of my console, here's a link to a third-party site showing the merkle root for Block 1000:

https://blockexplorer.com/block/00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09

**Comment by kokobird** [comment]
Also, same issue with Lesson 7, Chapter 5.

**Comment by jdnyzio** [comment]
Hey thanks for the feedback! The question should have specified that we were hoping for students to use the testnet to find the solution. 

The testnet is what our classroom terminal is connected to and a much more accessible way to use this software if you'd like to install it locally. 

You're totally right with the link you sent, but I instead clarified the answer to focus on the testnet to make the original solutions correct. 

Thanks for the feedback this was definitely confusing!

Block 1309: https://live.blockcypher.com/btc-testnet/block/00000000e1304e7f152f82069dc85b6522614785c74668bdaad79752f365658b/

Block 1000: https://live.blockcypher.com/btc-testnet/block/00000000373403049c5fff2cd653590e8cbe6f7ac639db270e7d1a7503d698df/
