### ISSUE TITLE
Probably documentation missing?

### ISSUE THREAD

**Issue by jperera84** [udacity/blockchain-nanodegree-issues#17]
Lesson 9, in the Introductory video the instructor said that is going to be more detail about cryptography down bellow the video, but there is nothing there, is missing any link to documentation?

**Comment by jdnyzio** [comment]
Hey, thanks for the feedback! I just updated the classroom to include an overview of the upcoming lesson. 

Lesson 9 Introduction: https://classroom.udacity.com/nanodegrees/nd1309/parts/c27351e7-b0ea-480c-bde9-a936817e4fe4/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/24197b75-77c9-476b-9595-7a1fe086d19b
