### ISSUE TITLE
Lesson 7, Video 14: Text missing

### ISSUE THREAD

**Issue by rastringer** [udacity/blockchain-nanodegree-issues#21]
'Feel free to read through the text below the video'

--Unfortunately no text

**Comment by jperera84** [comment]
Thanks for let us know @rastringer, we are on it.

**Comment by jdnyzio** [comment]
Thanks for the feedback! I just updated the classroom to include a brief overview of the upcoming lesson. 

https://classroom.udacity.com/nanodegrees/nd1309/parts/c27351e7-b0ea-480c-bde9-a936817e4fe4/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/04db8f80-0cda-4d49-9ccd-a2866d9daf5e/concepts/fbd846da-31a8-4025-a09f-d6438a857f6d?contentVersion=1.0.0&contentLocale=en-us
