### ISSUE TITLE
Lesson 9, Video 1: Missing text

### ISSUE THREAD

**Issue by rastringer** [udacity/blockchain-nanodegree-issues#27]
Brandy mentions there will be details of public and private blockchains listed below the video, nothing there unfortunately.

**Comment by jperera84** [comment]
Thanks for let us know @rastringer, we are solving this soon

**Comment by c0deist** [comment]
Came here to report the same.. 👍

**Comment by jdnyzio** [comment]
Thanks for the feedback! I updated this concept to include an overview of the upcoming lesson below the video. 

https://classroom.udacity.com/nanodegrees/nd1309/parts/c27351e7-b0ea-480c-bde9-a936817e4fe4/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/bad0043c-5c20-4201-a7c7-4112d3253f6c/concepts/24197b75-77c9-476b-9595-7a1fe086d19b
