### ISSUE TITLE
Broken Link- blockexplorer.com

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/blockchain-nanodegree-issues#31]
https://classroom.udacity.com/nanodegrees/nd1309/parts/c27351e7-b0ea-480c-bde9-a936817e4fe4/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/808abc06-4959-499c-9c31-54be1838096f/concepts/2638b316-58fb-48b3-b2a9-5730bfae8c14

Lesson 5: Blockchain Data Overview 
8. Explore Blockchain Data 

blockexplorer.com gives 404. 

Thank you!

**Comment by jperera84** [comment]
Thanks for let us know, this have been fixed.
