### ISSUE TITLE
Lesson 6: "Bitcoin Core - Overview" video subtitles

### ISSUE THREAD

**Issue by pahique** [udacity/blockchain-nanodegree-issues#35]
At 1:45, it sounds like "full node" instead of "4-node"

**Comment by pahique** [comment]
Please review all the subtitles from all the videos, I'm tired of opening issues like this, specially after having paid a lot of money for this course. Sorry

**Comment by ckurose** [comment]
Thanks so much for flagging these typos @pahique, sorry to hear they've been a nuisance to you... :/ The subtitling is done by an agency that does have real people reviewing them, but of course they aren't perfect. On the plus side, when we fix typos they learn the mistakes to watch out for and improve over time! We really appreciate you reporting these issues, but of course understand if you don't want to.
