### ISSUE TITLE
Problem Set: Bitcoin Codebase Questions Answers Are Related to Litecoin Source Code

### ISSUE THREAD

**Issue by ebisong** [udacity/blockchain-nanodegree-issues#4]
Under the Explore Bitcoins Codebase section. The 3 questions under 'Problem Set: Bitcoin Codebase' the answers refer to the the Litecoin source code rather than the bitcoin source code stated in the question.

**Comment by jlin27** [comment]
Thanks for calling that out. This was a remnant of an old exercise. All questions should be updated to correctly reference bitcoin codebase answer choices now.

**Comment by ebisong** [comment]
No problem. Thanks for the updates!
