### ISSUE TITLE
Lesson 5.Chapter 8 - Missing link below the video about  Bitcoin developer glossary

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#45]
In this video https://youtu.be/aNSwRWpd8L0, the instructor said: "If you are curious, you can go to the Bitcoin developer glossary to learn more. We put a link to this down below the video".

However, no link found below the video in Lesson 5.Chapter 8.

![image](https://user-images.githubusercontent.com/1788384/43041914-36961232-8d77-11e8-9280-55d4c5aaa036.png)
![image](https://user-images.githubusercontent.com/1788384/43041917-41ac9b6e-8d77-11e8-98e3-bd23d11b93aa.png)

**Comment by jperera84** [comment]
Thank you for the feedback we are going to correct this

**Comment by jperera84** [comment]
This has been fixed, thanks for the feedback
