### ISSUE TITLE
Lesson 6.Chapter 12 sending/receiving wallet identical

### ISSUE THREAD

**Issue by olyoberdorf** [udacity/blockchain-nanodegree-issues#46]
If you follow the instructions both wallets are copies of the original wallet.dat.  As a result you see the same balance in both and you immediately "receive" the coins in the sending wallet.  To do it properly, you have to set the wallet filename in the config but not copy the wallet.dat file.  Instead, let the client create the wallet for you for each of them, which it does automatically when you start the gui.

**Comment by jperera84** [comment]
Thank you for the feedback, we are on it.

**Comment by doug0072** [comment]
I just ran into the same problem, wasted a lot of time trying to figure out why it wasn't working. It's in the lesson called Testnet Wallet Transactions. [3.2.12]

**Comment by olyoberdorf** [comment]
It is not fixed.  Core 17 has *nothing* to do with this.

Look, just go do the "Testnet Wallet Transactions" exercise.  Follow your own instructions.  You will see that you can't properly send between the wallets because THEY ARE THE SAME WALLET.  Fix your instructions to not "duplicate this file" in step 2.  Instead actually read my ticket above.

**Comment by olyoberdorf** [comment]
Your Core 17 instructions appear after the Testnet Wallet Transactions lesson, which remains broken.

**Comment by jperera84** [comment]
I don't understand in this link you have the original version and it works for the version 0.16.3 of bitcoin: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/8abea3d8-b174-4f57-ad1d-03bc1bf0f68d/concepts/aaa10f87-54f7-4d4e-a142-db354895ad0a
But if you have v0.17 you need to follow the instructions in the next concept:
https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/8abea3d8-b174-4f57-ad1d-03bc1bf0f68d/concepts/0b3c8e84-9907-4fa1-b10e-1554900dab64
I tested both and I was able to do it successfully.
Do you mind specify what is the issue that you have?
Thanks
