### ISSUE TITLE
Lesson 6.Chapter 13 the blockcypher website does not function

### ISSUE THREAD

**Issue by olyoberdorf** [udacity/blockchain-nanodegree-issues#47]
I verified I am on testnet but transactions on the site look old and searching my tx id finds no matches.  I think their site is broken.

**Comment by jperera84** [comment]
Thank you for the feedback, we are going to check on this

**Comment by jperera84** [comment]
Thanks for the feedback, it is working as expected the page, the problem could be delays in the page but it is an outside service, right now looks ok, transactions are from 7 minutes ago.
