### ISSUE TITLE
Lesson 1 part 4: Sierra Leone election

### ISSUE THREAD

**Issue by ashishnitinpatil** [udacity/blockchain-nanodegree-issues#5]
In Lesson 1, part 4 Influence of BlockChain, there's an incorrect reference to Sierra Leone having hosted world's first blockchain powered election. They did demonstrate a use-case for this, but never actually used it in the election. More on this - https://techcrunch.com/2018/03/19/sierra-leone-government-denies-the-role-of-blockchain-in-its-recent-election/

**Comment by guicunha** [comment]
Oh great info, thanks

**Comment by mmjazzar** [comment]
Actually Canada working on a great project related to the voting elections.
As far as I know, they implemented a system merge between IOTA DAG, ethereum, and hyperledger.  You will find more resources in the below links. 

https://medium.com/iveyfintechclub/why-canada-should-become-a-blockchain-democracy-by-2019-faad0dd30d34 

https://globalnews.ca/news/3977745/ethereum-blockchain-canada-nrc/
