### ISSUE TITLE
Project 1 - Inconsistent output file format expectation

### ISSUE THREAD

**Issue by ashishnitinpatil** [udacity/blockchain-nanodegree-issues#53]
Project 1 - Managing your blockchain identity has expectations of `.txt` or `.md` on project.4 page, but only accepts `.md` (& others, but not `.txt`) on submission page. Even the validation success message on https://bitcoin-message-validation.firebaseapp.com/ is inconsistent with the output file format expectation.

**Comment by jperera84** [comment]
Hello, you can compress the file in Zip and upload the file without any problem

**Comment by ashishnitinpatil** [comment]
@jperera84 yep, there's not much hindrance for actual submission, but correcting the wording (".txt, .md, or .zip of any of those" wording in all 3 places, viz., project.4, submission page, validation app message) might save some time & won't confuse the submitter.

**Comment by jperera84** [comment]
This has been fixed
