### ISSUE TITLE
Lesson 6.12 - [ Grammar ] between vs among

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#60]
# Steps to reproduce

1. Navigate to lesson 6 - Term 1
2. Navigate to chapter 12
3. Read paragraph before the first head "Step 1: Find your Wallet".

# Actual

 "send transactions between multiple wallets that you own.". 

# Expected

 "send transactions ~~between~~ **among** multiple wallets that you own.".

**Comment by jperera84** [comment]
Thanks for the feedback, this has been fixed.
