### ISSUE TITLE
Lesson 7/Section 7 - Format list of definitions and one is missing

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#61]
The video mentions 3 Wallet commands. However, the commands section includes the definition of two commands only.

Also, the two commands definitions are written in the same line which is not consistent with previous lectures.

![image](https://user-images.githubusercontent.com/1788384/43672228-4f829f3c-97b2-11e8-8be8-a04570732f6e.png)

**Comment by jperera84** [comment]
Thanks for the feedback, this has been fixed.
