### ISSUE TITLE
Resources tab incorrect

### ISSUE THREAD

**Issue by kokobird** [udacity/blockchain-nanodegree-issues#65]
When within a lesson, the left-hand column of every page includes a tab for "Resources".

If you expand it, there's a link to "Forums".

The link takes us to "https://discussions.udacity.com/". However, course instructors in Slack has said we're NOT to use this resource.

Instead, this link should probably be going to https://knowledge.udacity.com/

**Comment by jperera84** [comment]
Thanks for the feedback, we are going to check on this.

**Comment by jperera84** [comment]
This has been fixed
