### ISSUE TITLE
Lesson 8/Section 3 confusion

### ISSUE THREAD

**Issue by kokobird** [udacity/blockchain-nanodegree-issues#66]
In the bullet-point list under "results", the 4th bullet point reads: "account - This is a deprecated. It’s set to “ “ as a default."

"This is a deprecated." <-- This doesn't make sense. Was a longer explanation intended to go here?

Also, if the default is set to " ", then why does this example show the value as "public faucet test"? This should be explained.

**Comment by jperera84** [comment]
Thanks for the feedback, we are going to check on this.

**Comment by jperera84** [comment]
This has been fixed
