### ISSUE TITLE
Knowledge layout/Firefox issue

### ISSUE THREAD

**Issue by olyoberdorf** [udacity/blockchain-nanodegree-issues#72]
When viewing the Knowledge site in Firefox on Windows 10, text for a question was not wrapped.  I was able to copy/paste to an editor to see what was clipped.

clipped text:
"n not remove the hash. Here is the Error message. please help solve this issue. Thanks."

Screenshot: https://1drv.ms/u/s!Ag4o0JpG3j6-k6FU0yGuhWKZkWSmaQ

**Comment by jperera84** [comment]
Thanks for the feedback, we really appreciate, this will be escalated to the product team.
