### ISSUE TITLE
BIPS and Froks section (Wrong and missed info)

### ISSUE THREAD

**Issue by yesshankar** [udacity/blockchain-nanodegree-issues#73]

**Comment by yesshankar** [comment]
![Lesson 1 Sec 10.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7c8698f67e6200111c2349/125516c66e82c728ace21e0d46c49189308d8de9dea98c46a71da1c46b0a65633b0ba92e7391a172fd1779555b0b1cfd150e5c45fff98b2ba6b769238f5f0de9d87f4366846c4ff8e7df46f554f832815d84b1b68b49c3ec352def8b8c48371c050ac4.jpg)

**Comment by jperera84** [comment]
Thanks for the feedback, this has been fixed
