### ISSUE TITLE
Lesson 5.3 ASCII Interchange and not Exchange

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#74]
# Actual 

> # Key Terms
> ASCII - American Standard Code for Information Exchange

# Expected

> # Key Terms
> ASCII - American Standard Code for Information Interchange

# How to solve?

Replace "Exchange" by "Interchange"

**Comment by jperera84** [comment]
This has been fixed, thanks for the feedback

**Comment by abdennour** [comment]
You are welcome @jperera84
