### ISSUE TITLE
Lesson Links to a Convicted Pedophile/Rapist Video

### ISSUE THREAD

**Issue by rtaibah** [udacity/blockchain-nanodegree-issues#76]
In section 3, [lesson 5](https://classroom.udacity.com/nanodegrees/nd1309/parts/c4ecd959-25d3-46c3-91ba-e5d79c638a34/modules/f3c9547d-af90-44e2-a5f5-c1c6160a2b2b/lessons/907321be-73ee-42d5-9b0d-5cf1175f9af5/concepts/e5c8fef4-380c-4f3a-b38b-8836038a00b0) you link to a youtube (first ascii video) video made by Carl Herold, who was charged with with child pornography production and raping his son. He was later found hanged in his prison cell...

Not sure if this is an 'issue', but just giving you a heads up on who you are linking to. The video is great, and his content was great, but some might find it creepy to watch.

**Comment by jperera84** [comment]
Thank you very much for this catch, We will change this

**Comment by jperera84** [comment]
This has been fixed
