### ISSUE TITLE
Link to an Unavailable Video in Lesson 5 Section 3

### ISSUE THREAD

**Issue by rtaibah** [udacity/blockchain-nanodegree-issues#77]
The video for the Base64 section links to an unavailable video.

[lesson](https://classroom.udacity.com/nanodegrees/nd1309/parts/c4ecd959-25d3-46c3-91ba-e5d79c638a34/modules/f3c9547d-af90-44e2-a5f5-c1c6160a2b2b/lessons/907321be-73ee-42d5-9b0d-5cf1175f9af5/concepts/e5c8fef4-380c-4f3a-b38b-8836038a00b0)

**Comment by jperera84** [comment]
I fixed this, thanks for the feedback
