### ISSUE TITLE
workspace set up windows

### ISSUE THREAD

**Issue by rbbinit** [udacity/blockchain-nanodegree-issues#80]
i already installed git in Windows.
i want to make my workspace using git. but it is difficult for me.
how can i find instruction ?

**Comment by jperera84** [comment]
Could you help me to clarify this please, what workspace are you trying to initialize? if what you mean is initialize your development environment you only need to install Node.js and npm: https://nodejs.org/en/download/
If you have any question feel free to post it in Knowledge.
