### ISSUE TITLE
escape of single quote was missing in curl command

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#81]
The following command does not work.

```sh
curl -X "POST" "http://localhost:8000/block" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "address": "142BDCeSGbXjWKaAnYXbMpZ6sbrSAo3DpZ",
  "star": {
    "dec": "-26° 29' 24.9",
    "ra": "16h 29m 1.0s",
    "story": "Found star using https://www.google.com/sky/"
  }
}'
```

This command was used under the title "Example: Block with star object endpoint".

It does not work because `-26° 29' 24.9` contains a single quote that should be escaped as following  `-26° 29'\'' 24.9`.

```sh
curl -X "POST" "http://localhost:8000/block" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "address": "142BDCeSGbXjWKaAnYXbMpZ6sbrSAo3DpZ",
  "star": {
    "dec": "-26° 29'\'' 24.9",
    "ra": "16h 29m 1.0s",
    "story": "Found star using https://www.google.com/sky/"
  }
}'

```

# Related Lecture

https://classroom.udacity.com/nanodegrees/nd1309/parts/c4ecd959-25d3-46c3-91ba-e5d79c638a34/modules/f3c9547d-af90-44e2-a5f5-c1c6160a2b2b/lessons/532fc24f-cb8c-4b0b-9e8b-c0d125bf84b3/concepts/acd6b084-6c8a-48f4-aa78-c9b3ae55b80e

**Comment by jperera84** [comment]
Thanks for the feedback, I fixed this
