### ISSUE TITLE
Confusing UI/UX of sidebar showing curriculam details

### ISSUE THREAD

**Issue by arshdkhn1** [udacity/blockchain-nanodegree-issues#82]
IMHO, the sidebar which shows curriculam parts and lessons is a bit confusing. When you click on a section/part of curriculam, the lessons belonging to that section/parts are shown. I would suggest to have a top heading which shows what's the current part the user is looking at. 

I got a bit confused while moving from part 1 to part 2 as part 1's name is a bit similar to part2's first lesson. This might not be issue for all but I thought it would be better reporting it.

**Comment by jperera84** [comment]
Thanks for the reporting, it is always welcome, I will escalate this to the classroom experience team.
