### ISSUE TITLE
Links on blockchain identity - lesson 3 are redirecting to a page which can't be opened.

### ISSUE THREAD

**Issue by arshdkhn1** [udacity/blockchain-nanodegree-issues#83]
<img width="581" alt="screen shot 2018-09-11 at 10 34 22 pm" src="https://user-images.githubusercontent.com/16819670/45375821-bad5ae80-b613-11e8-9f1b-85964caf7368.png">

whenever i open ^ these links, i get -

<img width="1360" alt="screen shot 2018-09-11 at 10 41 33 pm" src="https://user-images.githubusercontent.com/16819670/45375870-db056d80-b613-11e8-8ab5-fba9ee73f40b.png">

**Comment by jperera84** [comment]
Thanks for the feedback, those links weren't necessary, so we delete those
