### ISSUE TITLE
Missing closing grave accent on bltcore-message text.

### ISSUE THREAD

**Issue by arshdkhn1** [udacity/blockchain-nanodegree-issues#84]
i believe the template udacity is using on backend uses grave-accent for codes.. On bitcoin identities, lesson 5, search for `bitcore-message`

**Comment by jperera84** [comment]
Thanks for the feedback, We are going to analyze this and take an action.

**Comment by jperera84** [comment]
I cannot reproduce it, please feel free to reopen it and attach a classroom link. Thanks
