### ISSUE TITLE
Video shows wrong param name for bitcoin.conf file

### ISSUE THREAD

**Issue by arshdkhn1** [udacity/blockchain-nanodegree-issues#85]
In Part 3 blochain data, lesson 2 - video 10 , for opening regnet, video shows regnet = 1 where it should be regtest = 1

**Comment by jperera84** [comment]
Thanks for the feedback, We are going to analyze this and take an action.

**Comment by jperera84** [comment]
In Part 3, Lesson 2, Concept 10 in the video I don't find where there is a typo: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/8abea3d8-b174-4f57-ad1d-03bc1bf0f68d/concepts/933f165a-12b8-402a-9591-7193463d3d41

Instead in Concept 11, in the text down bellow the video everything looks correct:
"Access regnet: regtest = 1 in bitcoin.conf file"

"regnet" is the name of the network and the parameter is "regtest"

**Comment by jperera84** [comment]
Closing this for now.
