### ISSUE TITLE
the options in quiz question problem are not right  on Part 3 lesson 4 video 10 - transaction data

### ISSUE THREAD

**Issue by arshdkhn1** [udacity/blockchain-nanodegree-issues#86]

**Comment by jperera84** [comment]
Thanks for the feedback, We are going to analyze this and take an action.

**Comment by jperera84** [comment]
This is the link for Part 3, Lesson 4, Concept 10: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/970128bc-c405-4a22-8fed-d3f56d5dfac1/concepts/f3bedf30-8e9c-454a-ad87-49396ed0eafe
I didn't find any Quiz, could you verify and share the link of the classroom?
Thanks

**Comment by jperera84** [comment]
I cannot reproduce it. Please feel open to reopen it.
