### ISSUE TITLE
[Lesson 1 Smart Contract] Typo "An" instead of "And"

### ISSUE THREAD

**Issue by abdennour** [udacity/blockchain-nanodegree-issues#90]
You said "An of course Solidity, "

But the  Expected is "And of course Solidity, "

# Related Lecture:

- https://classroom.udacity.com/nanodegrees/nd1309/parts/2e478a90-310b-4703-aa20-efec12eb258c/modules/f1d81730-f430-46fb-a490-0f260a65f997/lessons/a486c88b-a0d6-441a-b8c0-b7f62504d31e/concepts/2cb145ee-decd-4aaa-b167-65590ade4bcb

**Comment by jperera84** [comment]
This has been fixed, thanks
