### ISSUE TITLE
Lesson 5 Private Block Chain - LevelDB to Persist Data

### ISSUE THREAD

**Issue by paramountgroup** [udacity/blockchain-nanodegree-issues#98]
Sample reference code on the page not the same as in levelSandbox.js terminal code

The constant declaration (this does not run):

const level = require('level');
const chainDB = './chaindata';
const db = level(chainDB);

Should be objects:

let level = require('level');
let chainDB = './chaindata';
let db = level(chainDB);

**Comment by jperera84** [comment]
Thanks I changed the code reference to match the terminal.
